=encoding utf8

=head1 NAME

App::p6al - Perl 6 Archive Listing

=head1 DESCRIPTION

P6AL (pronounced “sixal”) is a web application that lists and searches Perl 6
archives and packages.

=head2 Requirements

=over

=item *
On every page, a search field is presented. When submitted, the application
searches through archive and package names and descriptions and presents a
search result for each archive and package found. Following a search result
takes the user to the rendered readme or POD documentation of the archive or
package respectively.

=item *
For each archive or package, its documentation page lists metadata about the
author, dependencies, and source location, if known.

=item *
For each archive or package, its documentation page presents a list of
versions that the user can follow to go to the documentation page for that
version.

=item *
For each archive or package, its documentation page tells the user how to
obtain the archive or package using Nix, Zef, or HTTPS.

=item *
The application is fully functional regardless of whether the user has
enabled or disabled the execution of ECMAScript code in their web browser.

=back
