=encoding utf8

=head1 NAME

App::p6al - Perl 6 Archive Listing

=head1 DESCRIPTION

P6AL (pronounced “sixal”) is a web application that lists and searches Perl 6
distributions and comp units.

=head2 Requirements

=over

=item *
On every page, a search field is presented. When submitted, the application
searches through distribution and comp unit names and descriptions and
presents a search result for each distribution and comp unit found. Following
a search result takes the user to the rendered readme or POD documentation of
the distribution or comp unit respectively.

=item *
For each distribution or comp unit, its documentation page lists metadata
about the author, dependencies, and source location, if known.

=item *
For each distribution or comp unit, its documentation page presents a list of
versions that the user can follow to go to the documentation page for that
version.

=item *
For each distribution or comp unit, its documentation page tells the user how
to obtain the distribution or comp unit using Nix, Zef, or HTTPS.

=item *
The application is fully functional regardless of whether the user has
enabled or disabled the execution of ECMAScript code in their web browser.

=back
